[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name              tail
    Path              /logs/browser-events.ndjson
    Tag               browser.events
    Read_from_Head    True
    Refresh_Interval  2
    Skip_Long_Lines   On
    DB                /fluent-bit/state/tail.db
    DB.Sync           Normal
    Parser            ndjson

[FILTER]
    Name   modify
    Match  browser.events
    Add    programname  browser-event-collector
    Add    Hostname     ${NODE_NAME}
    Rename log          Payload

[OUTPUT]
    Name                opensearch
    Match               browser.events
    Host                ${OPENSEARCH_HOST}
    Port                ${OPENSEARCH_PORT}
    HTTP_User           ${OPENSEARCH_USER}
    HTTP_Passwd         ${OPENSEARCH_PASS}
    Logstash_Format     On
    Logstash_Prefix     ${OS_INDEX_PREFIX}
    Logstash_DateFormat %Y.%m.%d
    Replace_Dots        On
    Suppress_Type_Name  On
    Retry_Limit         False

[OUTPUT]
    Name   stdout
    Match  browser.events
